In [ ]:
#creation of relational database
import sqlite3

conn = sqlite3.connect("student.db")
c = conn.cursor()

try:
    
    c.execute('''CREATE TABLE student (
        student_id text PRIMARY KEY NOT NULL,
        first_name text NOT NULL,
        last_name text NOT NULL,
       FOREIGN KEY (student_id) REFERENCES course(student_id) )''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()

try:
    c.execute('''CREATE TABLE course (
        course_id text PRIMARY KEY NOT NULL,
        course_name text NOT NULL,
        credit_hour int NOT NULL,
        instructor_name test NOT NULL,
       FOREIGN KEY (instructor_name) REFERENCES instructor(instructor_name),
       FOREIGN KEY (course_id) REFERENCES enrollment(course_id))''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()

try:
    c.execute('''CREATE TABLE enrollment (
        student_id text NOT NULL,
        course_id text NOT NULL,
        FOREIGN KEY (student_id) REFERENCES student (student_id),
       fOREIGN KEY (course_id) REFERENCES enrollment(course_id))''')
    
        
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()

try:
    c.execute('''CREATE TABLE instructor (
        instructor_name text PRIMARY KEY NOT NULL,
        instructor_lastname NOT NULL,
       FOREIGN KEY (instructor_name) REFERENCES course(instructor_name) )''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()

try:
    c.execute('''CREATE TABLE faculty (
        faculty_id text PRIMARY KEY NOT NULL,
        faculty_first_name text NOT NULL,
        faculty_last_name text NOT NULL,
       FOREIGN KEY (faculty_id) REFERENCES course(student_id) )''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()
    


try:
    c.execute('''CREATE TABLE grades (
        student_id text  NOT NULL,
        course_id NOT NULL,
       grades REAL )''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()

try:
    c.execute('''CREATE TABLE users (
        id text PRIMARY KEY NOT NULL,
       usernname text  NOT NULL,
       password text NOT NULL,
       access NOT NULL )''')
except sqlite3.OperationalError as e:
    print('sqlite error:', e.args[0])  # table already exists

conn.commit()